-- Disposable test databases only: delivered callbacks cannot be undone remotely.
DROP TRIGGER aurix_human_hold ON aurix_lead_links;
DROP FUNCTION aurix_human_hold();
DROP FUNCTION start_aurix_voice(uuid,uuid,text);
ALTER TABLE aurix_lead_links DROP COLUMN execution_lease_until;
DROP TRIGGER aurix_calendar_guard ON bookings;
DROP FUNCTION aurix_calendar_guard();
DROP FUNCTION book_aurix_confirmed(uuid,uuid,text,uuid,timestamptz);
DROP INDEX aurix_sms_receipt_uidx;
DROP TRIGGER aurix_preference_lock ON suppression_list;
DROP FUNCTION aurix_lock_preference();
DROP TRIGGER aurix_workflow_failure ON workflow_runs;
DROP FUNCTION aurix_workflow_failure();
DROP FUNCTION finish_aurix_qualification(uuid,jsonb,boolean);
DROP FUNCTION start_aurix_workflow(uuid,uuid,jsonb);
DROP TRIGGER aurix_preserve_workflow ON aurix_lead_links;
DROP FUNCTION aurix_preserve_run();
DROP TRIGGER aurix_booking_lifecycle ON bookings;
DROP FUNCTION aurix_booking_changed();
DROP FUNCTION aurix_explicit_opt_in(uuid,text,text,jsonb);
DROP TRIGGER aurix_suppression_insert ON suppression_list;
DROP FUNCTION aurix_suppression_changed();
DROP TRIGGER aurix_callback_immutable ON aurix_callback_outbox;
DROP FUNCTION protect_aurix_callback();
DROP FUNCTION enqueue_aurix_event(uuid,uuid,text,text,jsonb);
DROP TABLE aurix_consent_receipts;
DROP TABLE aurix_booking_links;
DROP TABLE aurix_callback_outbox;
ALTER TABLE aurix_lead_links DROP COLUMN workflow_run_id;
ALTER TABLE aurix_lead_links DROP COLUMN consent_override;
DROP INDEX aurix_contact_owner_uidx;
UPDATE aurix_lead_links SET workflow_state='human_hold' WHERE workflow_state IN ('running','completed','failed');
ALTER TABLE aurix_lead_links DROP CONSTRAINT aurix_lead_links_workflow_state_check;
ALTER TABLE aurix_lead_links ADD CONSTRAINT aurix_lead_links_workflow_state_check CHECK(workflow_state IN ('hold_for_qa','hold_for_consent','human_hold'));
ALTER TABLE aurix_installations DROP COLUMN callback_url;
ALTER TABLE aurix_installations DROP COLUMN config;
ALTER TABLE aurix_installations DROP COLUMN qa_evidence;
